from setuptools import setup, find_packages

setup(
    dependency_links=[],
    name="stockplot",
    packages=find_packages(exclude=["tests"]),
    author="Thomas McInally",
    url="https://github.com/Thomas-mcinally/stockplot",
    long_description_content_type="text/markdown",
    python_requires=">=3.10",
    install_requires=[
        "appdirs==1.4.4",
        "beautifulsoup4==4.12.2; python_full_version >= '3.6.0'",
        "certifi==2023.11.17; python_version >= '3.6'",
        "charset-normalizer==3.3.2; python_full_version >= '3.7.0'",
        "contourpy==1.2.0; python_version >= '3.9'",
        "cycler==0.12.1; python_version >= '3.8'",
        "fonttools==4.47.0; python_version >= '3.8'",
        "frozendict==2.3.10; python_version >= '3.6'",
        "html5lib==1.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "idna==3.6; python_version >= '3.5'",
        "kiwisolver==1.4.5; python_version >= '3.7'",
        "lxml==5.0.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "matplotlib==3.8.2; python_version >= '3.9'",
        "mplfinance==0.12.10b0",
        "multitasking==0.0.11",
        "numpy==1.26.2; python_version >= '3.9'",
        "packaging==23.2; python_version >= '3.7'",
        "pandas==2.1.4; python_version >= '3.9'",
        "peewee==3.17.0",
        "pillow==10.1.0; python_version >= '3.8'",
        "pyparsing==3.1.1; python_full_version >= '3.6.8'",
        "python-dateutil==2.8.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'",
        "pytz==2023.3.post1",
        "requests==2.31.0; python_version >= '3.7'",
        "six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'",
        "soupsieve==2.5; python_version >= '3.8'",
        "tzdata==2023.4; python_version >= '2'",
        "urllib3==2.1.0; python_version >= '3.8'",
        "webencodings==0.5.1",
        "yfinance==0.2.33",
    ],
    version="2.0.3",
    entry_points={"console_scripts": ["stockplot = stockplot.main:main"]},
)
